# Generated by Django 5.2.4 on 2025-07-18 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentagem'), ('fixed_amount', 'Valor Fixo')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Valor do desconto (ex: 10 para 10% ou R$10,00).', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True, help_text='Marque para ativar a promoção.')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
