# Generated by Django 5.2.4 on 2025-07-18 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Porcentagem')], max_length=20),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, help_text='Valor do desconto (ex: 10 para 10%).', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
