# Generated by Django 5.2.4 on 2025-07-10 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco_extra', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Sabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('max_sabores', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('pizza', 'Pizza'), ('bebida', 'Bebida'), ('sobremesa', 'Sobremesa')], default='pizza', max_length=20),
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Produtos.produto')),
                ('bordas_disponiveis', models.ManyToManyField(blank=True, to='Produtos.borda')),
                ('sabores_disponiveis', models.ManyToManyField(to='Produtos.sabor')),
                ('tamanhos_disponiveis', models.ManyToManyField(to='Produtos.tamanho')),
            ],
            bases=('Produtos.produto',),
        ),
    ]
