# Generated by Django 5.2.4 on 2025-07-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0002_borda_sabor_tamanho_produto_categoria_pizza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='tamanhos_disponiveis',
        ),
        migrations.AddField(
            model_name='pizza',
            name='max_sabores',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Tamanho',
        ),
    ]
