# Generated by Django 5.2.4 on 2025-07-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0003_remove_pizza_tamanhos_disponiveis_pizza_max_sabores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabor',
            name='preco_extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
