# Generated by Django 5.2.4 on 2025-07-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0004_sabor_preco_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('pizza', 'Pizza'), ('bebida', 'Bebida'), ('sobremesa', 'Sobremesa'), ('petisco', 'Petisco')], default='pizza', max_length=20),
        ),
    ]
