# Generated by Django 5.2.4 on 2025-07-11 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0001_initial'),
        ('Produtos', '0004_sabor_preco_extra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='data',
            new_name='data_pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(default='Em andamento', max_length=50),
        ),
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observacao', models.TextField(blank=True)),
                ('borda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Produtos.borda')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Pedidos.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produtos.produto')),
                ('sabores', models.ManyToManyField(blank=True, to='Produtos.sabor')),
            ],
        ),
        migrations.DeleteModel(
            name='ItemPedido',
        ),
    ]
