# Generated by Django 5.2.4 on 2025-07-16 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0008_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=0.0, help_text='Desconto percentual aplicado ao preço total dos itens do combo.', max_digits=5)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='combos.combo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_part_of_combos', to='products.product')),
            ],
            options={
                'unique_together': {('combo', 'product')},
            },
        ),
    ]
