# Generated by Django 5.2.4 on 2025-07-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='desconto_percentual',
        ),
    ]
