# Generated by Django 5.2.4 on 2025-07-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combos', '0002_remove_combo_desconto_percentual'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='combos/'),
        ),
    ]
