# Generated by Django 5.2.4 on 2025-07-15 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_product'),
        ('products', '0002_optiontype_pizzaborder_pizzaflavor_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='order_items', to='products.option'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pizza_border',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.pizzaborder'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pizza_flavors',
            field=models.ManyToManyField(blank=True, related_name='order_items', to='products.pizzaflavor'),
        ),
    ]
