# Generated by Django 5.2.4 on 2025-07-16 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combos', '0001_initial'),
        ('orders', '0004_alter_order_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='parent',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items_as_combo', to='combos.combo'),
        ),
    ]
