# Generated by Django 5.2.4 on 2025-07-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orderitem_parent_orderitem_combo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='observation',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
