# Generated by Django 5.2.4 on 2025-07-18 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_observation'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='applied_promotion',
            field=models.ForeignKey(blank=True, help_text='A promoção que foi aplicada a este item no momento da compra.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_order_items', to='promotions.promotion'),
        ),
    ]
