# Generated by Django 5.2.4 on 2025-07-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='single',
            field=models.BooleanField(default=True),
        ),
    ]
