# Generated by Django 5.2.4 on 2025-07-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_single'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='available_option_types',
            field=models.ManyToManyField(blank=True, related_name='products_with_this_option_type', to='products.optiontype'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_pizza_borders',
            field=models.ManyToManyField(blank=True, related_name='products_with_this_border', to='products.pizzaborder'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_pizza_flavors',
            field=models.ManyToManyField(blank=True, related_name='products_with_this_flavor', to='products.pizzaflavor'),
        ),
    ]
