# Generated by Django 5.2.4 on 2025-07-15 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_image_product_available_option_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='single',
        ),
    ]
