# Generated by Django 5.2.4 on 2025-07-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_category_single'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_flavors',
            field=models.PositiveIntegerField(blank=True, help_text='Número máximo de seções de sabor para pizzas (ex: 2 para meio a meio, 4 para quatro sabores). Deixe em branco para produtos não-pizza.', null=True),
        ),
    ]
