# Generated by Django 5.2.4 on 2025-07-16 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='max_flavors',
            new_name='max_flavor_sections',
        ),
    ]
