# Generated by Django 5.2.4 on 2025-07-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_max_flavors_product_max_flavor_sections'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promotions',
            field=models.ManyToManyField(blank=True, related_name='products_on_promotion', to='promotions.promotion'),
        ),
    ]
