# Generated by Django 5.2.4 on 2025-07-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_promotions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
